spring.application.name=spring-ai-rag-demo
spring.threads.virtual.enabled=true

# Базовый URL и ключ OpenRouter
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${OPENROUTER_API_KEY}

# Динамический роутер для бесплатных моделей
spring.ai.openai.chat.model=openrouter/free

# Отключение советника так как бесплатные модели не всегда стабильны с Tool Calling
spring.ai.chat.client.tool-search-advisor.enabled=false

# External knowledge base
knowledge.file=${KNOWLEDGE_FILE:data/delivery-standards.txt}

