spring.application.name=spring-ai-rag-demo
spring.threads.virtual.enabled=true

# Базовый URL и ключ OpenRouter
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${OPENROUTER_API_KEY}

# Динамический роутер для бесплатных моделей
spring.ai.openai.chat.model=openrouter/free

# Отключение советника так как бесплатные модели не всегда стабильны с Tool Calling
spring.ai.chat.client.tool-search-advisor.enabled=false

# External knowledge base
knowledge.file=${KNOWLEDGE_FILE:data/checklist-knowledge-base.example.json}
knowledge.vector-store.ingestion.enabled=true

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/rag}
spring.datasource.username=${DB_USERNAME:rag}
spring.datasource.password=${DB_PASSWORD:rag}

# PGVector
spring.ai.vectorstore.pgvector.initialize-schema=true

# Embedding model
spring.ai.openai.embedding.model=liquid/lfm-2.5-embedding-350m:free
spring.ai.openai.embedding.dimensions=1024

